apiVersion: v1
kind: Service
metadata:
  name: server
spec:
  selector:
    app: server
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
      name: http
  type: NodePort
status:
  loadBalancer: {}

---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: server
spec:
  hosts:
  - "*"
  gateways:
  - microservice-gateway
  http:
  - match:
    - uri:
        prefix: /server/
    rewrite:
      uri: /api/
    route:
    - destination:
        port:
          number: 80
        host: server.default.svc.cluster.local