name: CI
on:
  - pull_request
  - push
jobs:
  job1:
    runs-on: ubuntu-latest
    name: build and deploy to minikube
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Start Kubernetes minikube
        uses: medyagh/setup-minikube@master
      - name: Try the Kubernetes cluster
        run: kubectl get pods -A
      - name: Deploy the images to minikube
        run: |
          cd kubernetes
          kubectl apply -f database.yaml